openapi: 3.0.0
servers:
  - description: Production server
    url: redmobile-cloud-message.herokuapp.com/v1
info:
  description: This is a Cloud Message API for RedMobile
  version: "1.0.0"
  title: Cloud Message Api for RedMobile
  contact:
    url: 'https://github.com/okhiroyuki/redmobile-cloud-message'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/okhiroyuki/redmobile-cloud-message/main/LICENSE'
paths:
  /message/send:
    post:
      operationId: sendMessage
      description: sending cloud messages to redmobile
      responses:
        '200':
          description: Send Success
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
        description: Inventory item to add
components:
  schemas:
    Message:
      type: object
      required:
        - token
        - data
      properties:
        token:
          type: string
          description: Token obtained by redmobile
          example: "bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1..."
        data:
          type: object
          description: Custom Key-Value Pairs
          example: '{"Nick" : "Mario", "Room" : "PortugalVSDenmark"}'
